User.create(email: "mich@test.com", username: "micholi", password: "brooklyn")
User.create(email: "timmycat@email.com", username: "Timmy", password: "catnip")
User.create(email: "june@mail.com", username: "Offred", password: "praisebe")
Network.create(name: "HBO")
Network.create(name: "NBC")
Network.create(name: "Hulu")
Network.create(name: "Netflix")
Show.create(name: "Game of Thrones", genre: "Fantasy", description: "Medieval fantasy about power struggles among the Seven Kingdoms of Westeros.", air_date: "Returns in 2019", user_id: 1, network_id: 1)
Show.create(name: "This is Us", genre: "Drama", description: "Dramedy that chronicles the lives and struggles of the Pearson family across three decades.", air_date: "Tuesdays at 9pm", user_id: 1, network_id: 2)
Show.create(name: "The Handmaid's Tale", genre: "Drama", description: "Adapted from the classic novel by Margaret Atwood, The Handmaid's Tale is the story of life in the dystopia of Gilead, a totalitarian society in what was formerly the United States.", air_date: "New episodes stream on Wednesdays", user_id: 3, network_id: 3)
Show.create(name: "Arrested Development", genre: "Comedy", description: "It's the Emmy-winning story of a wealthy family that lost everything, and the one son who had no choice but to keep them all together.", air_date: "New episodes stream on May 29, 2018", user_id: 2, network_id: 4)
